all:

  money:
    emphasize_above: 100

  sf_admin_dash:
    categories:
      Finanse:
        items:
          Wydatki:
            url: event
            image: full-shopping-cart-icon.png
          Przychody:
            url: income
            image: wallet-icon.png
          Rodzaje wydatk√≥w:
            url: category
            image: preferences.png
