all:

  chart_size:
    width: 600
    height: 400

  outcome:
    expensive: 100

  sf_admin_dash:
    categories:
      Finanse:
        items:
          Wydatki:
            url: outcome
            image: full-shopping-cart-icon.png
          Rodzaje wydatków:
            url: outcome_category
            image: preferences.png
          Przychody:
            url: income
            image: wallet-icon.png
          Rodzaje przychodów:
            url: income_category
            image: preferences.png
      Wykresy:
        items:
          Wg kategorii:
            url: chart_category_pie
            image: misc-stats-icon.png
          Bilans miesięczny:
            url: chart_monthly_balance_bars
            image: misc-stats-icon.png
