category:
  class: sfDoctrineRouteCollection
  options:
    model:                Category
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

income:
  class: sfDoctrineRouteCollection
  options:
    model:                Income
    module:               income
    prefix_path:          /income
    column:               id
    with_wildcard_routes: true

event:
  class: sfDoctrineRouteCollection
  options:
    model:                Event
    module:               event
    prefix_path:          /event
    column:               id
    with_wildcard_routes: true

chart_category_pie:
  url:   /chart/category-pie/:mode
  param: { module: chart, action: categoryPie, mode: execute }

homepage:
  url:   /
  param: { module: sfAdminDash, action: dashboard }
